language: perl
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
      after_success:
      - travis_wait 30 cover -test -report coveralls
    - perl: 5.12
      env: COVERAGE=0 
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - cpanm --notest CPAN::Uploader
  - cpanm --notest Devel::Cover
  - cpanm --notest Devel::Cover::Report::Coveralls
# override default build command in order to increase wait timeout
script: perl Build.PL && ./Build && travis_wait 30 ./Build test
deploy:
  provider: script
  script: ./Build deploy
  skip_cleanup: true
  on:
    branch: master
    tags: true
    perl: 5.24

